name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test || echo "Tests failed" > test_status.txt
        continue-on-error: true

      - name: Save current commit hash
        run: echo "${{ github.sha }}" > current_commit.txt

      - name: Upload current commit hash
        uses: actions/upload-artifact@v3
        with:
          name: current-commit
          path: current_commit.txt

      - name: Download last successful commit hash
        uses: actions/download-artifact@v3
        with:
          name: last-successful-commit

      - name: Run bisect
        env:
          BAD_HASH: ${{ github.sha }}
          GOOD_HASH: $(cat last_successful_commit.txt || echo "initial_commit_hash")
        run: python bob.py

      - name: Check test results
        run: |
          if grep -q "Tests failed" test_status.txt; then
            echo "Tests did not pass"
            exit 1
          else
            echo "Tests passed"
          fi
